#docker compose version to deploy
# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: nestjs_app
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_HOST: postgres
#       DATABASE_PORT: 5432
#       DATABASE_USER: postgres
#       DATABASE_PASSWORD: postgres
#       DATABASE_NAME: nest_db
#     networks:
#       - nest_network

#   postgres:
#     image: postgres:15
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: nest_db
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - nest_network

# networks:
#   nest_network:

# volumes:
#   postgres_data:

#docker compose version to run the api locally and the database in docker
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_ecommerce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - nest_network

networks:
  nest_network:

volumes:
  postgres_data: